/**
 * Activity: Execute Campaign via Amazon SES
 * Sends approved email payload directly via AWS SES v2 API.
 * Uses native fetch + AWS Signature v4 — no Node.js built-ins, compatible with Cloudflare Workers.
 * Falls back to a safe error result if the SES call fails.
 *
 * Write-back: PATCHes `strike_campaigns` → status='sent', sent_at=NOW(), ses_message_id.
 */
import type { Env } from '../index';
import { patchRow } from '../utils/supabase';
import { signAwsRequest, type AwsCredentials } from '../utils/aws-signer';

/**
 * HMAC-sign the unsubscribe link parameters so the public endpoint can verify the
 * link was generated by us (prevents bulk forged unsubscribes / list poisoning).
 */
async function signUnsubscribeToken(secret: string, email: string, campaignId: number): Promise<string> {
    const key = await crypto.subtle.importKey(
        'raw',
        new TextEncoder().encode(secret),
        { name: 'HMAC', hash: 'SHA-256' },
        false,
        ['sign'],
    );
    const mac = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(`${email.toLowerCase()}:${campaignId}`));
    // base64url
    return btoa(String.fromCharCode(...new Uint8Array(mac)))
        .replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

export interface SesExecuteInput {
    campaignId: number;  // BIGSERIAL
    workflowId: string;
    emailSubject: string;
    emailBody: string;
    recipientEmail: string;
    senderEmail: string;      // The rotated sender address (e.g. fred@ppalink.com)
    senderName?: string;       // Display name (e.g. "Fred Posinelli")
    replyToEmail?: string;     // Optional reply-to override
    subjectVersion?: string;   // A/B test version sent ('A' or 'B')
}

export interface SesCampaignResult {
    campaignId: number;
    sesMessageId: string;
    status: string;
    scheduledAt: string;
    error: string | null;
}

export async function executeCampaignSes(env: Env, input: SesExecuteInput): Promise<SesCampaignResult> {
    console.log(`🚀 Executing SES campaign | Campaign #${input.campaignId} | Workflow: ${input.workflowId} | Sender: ${input.senderEmail}`);

    try {
        // Recipient sanity gate — refuse malformed addresses and known enrichment placeholders
        const recipients = input.recipientEmail.split(',').map(e => e.trim()).filter(Boolean);
        const emailRe = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        const badRecipients = recipients.filter(r =>
            !emailRe.test(r) ||
            r.toLowerCase().includes('email_not_unlocked') ||
            r.toLowerCase().endsWith('@domain.com')
        );
        if (recipients.length === 0 || badRecipients.length > 0) {
            throw new Error(`Invalid recipient email rejected before send: "${input.recipientEmail}"`);
        }

        const credentials: AwsCredentials = {
            accessKeyId: env.AWS_ACCESS_KEY_ID,
            secretAccessKey: env.AWS_SECRET_ACCESS_KEY,
            region: env.AWS_REGION || 'us-east-1',
        };

        const region = credentials.region;
        const sesUrl = `https://email.${region}.amazonaws.com/v2/email/outbound-emails`;

        // Build SES v2 SendEmail request body
        const senderDisplay = input.senderName
            ? `${input.senderName} <${input.senderEmail}>`
            : input.senderEmail;

        // Drafts are generated as plaintext (the prompt forbids HTML). Sending raw text as the
        // HTML part collapses every newline, so the email renders as one run-on paragraph.
        // Escape the text and convert newlines for HTML; keep the raw text for the Text part.
        const escapeHtml = (s: string) => s
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;');
        const htmlBody = escapeHtml(input.emailBody).replace(/\r?\n/g, '<br>\n');

        // Sign the unsubscribe link so the public endpoint can reject forged requests.
        let unsubscribeSig = '';
        if (env.WORKER_SECRET) {
            try {
                unsubscribeSig = await signUnsubscribeToken(env.WORKER_SECRET, input.recipientEmail, input.campaignId);
            } catch (sigErr) {
                console.warn('⚠️ Failed to sign unsubscribe token (link will be unsigned):', sigErr);
            }
        }

        const requestBody = JSON.stringify({
            Content: {
                Simple: {
                    Subject: {
                        Data: input.emailSubject,
                        Charset: 'UTF-8',
                    },
                    Body: {
                        Html: {
                            Data: htmlBody,
                            Charset: 'UTF-8',
                        },
                        Text: {
                            Data: input.emailBody,
                            Charset: 'UTF-8',
                        },
                    },
                    Headers: [
                        {
                            Name: 'List-Unsubscribe',
                            Value: `<https://ppa-apex-platform.fred-78e.workers.dev/api/v1/unsubscribe?email=${encodeURIComponent(input.recipientEmail)}&c=${input.campaignId}${unsubscribeSig ? `&sig=${unsubscribeSig}` : ''}>, <mailto:unsubscribe@${input.senderEmail.split('@')[1]}?subject=Unsubscribe>`,
                        },
                        {
                            Name: 'List-Unsubscribe-Post',
                            Value: 'List-Unsubscribe=One-Click',
                        },
                    ],
                },
            },
            Destination: {
                ToAddresses: recipients,
            },
            FromEmailAddress: senderDisplay,
            ReplyToAddresses: [input.replyToEmail || input.senderEmail],
            // Custom headers for reply threading
            EmailTags: [
                { Name: 'campaign_id', Value: String(input.campaignId) },
                { Name: 'workflow_id', Value: input.workflowId },
            ],
            // Enable SES configuration set for event tracking (bounces, opens, clicks)
            ...(env.SES_CONFIGURATION_SET ? { ConfigurationSetName: env.SES_CONFIGURATION_SET } : {}),
        });

        const headers: Record<string, string> = {
            'Content-Type': 'application/json',
        };

        const signedHeaders = await signAwsRequest(
            'POST',
            sesUrl,
            headers,
            requestBody,
            credentials,
            'ses'
        );

        const response = await fetch(sesUrl, {
            method: 'POST',
            headers: signedHeaders,
            body: requestBody,
        });

        if (!response.ok) {
            const errText = await response.text();
            throw new Error(`SES API error ${response.status}: ${errText}`);
        }

        const data = await response.json() as {
            MessageId?: string;
        };

        const sesMessageId = data.MessageId || `ses-${crypto.randomUUID().slice(0, 12)}`;
        const now = new Date().toISOString();

        const result: SesCampaignResult = {
            campaignId: input.campaignId,
            sesMessageId,
            status: 'sent',
            scheduledAt: now,
            error: null,
        };

        console.log(`✅ Campaign delivered via SES: ${sesMessageId} → ${input.recipientEmail}`);

        // Write-back: mark campaign as sent in Supabase
        if (input.campaignId > 0) {
            const writeResult = await patchRow(env, 'strike_campaigns', {
                status: 'sent',
                sent_at: now,
                ses_message_id: sesMessageId,
                sender_email: input.senderEmail,
                ...(input.subjectVersion ? { subject_version_sent: input.subjectVersion } : {}),
            }, 'id', input.campaignId);

            if (writeResult.ok) {
                console.log(`💾 Campaign status updated to 'sent' (id: ${input.campaignId})`);
            }
        }

        return result;
    } catch (err) {
        const errorMsg = err instanceof Error ? err.message : String(err);
        console.error(`❌ SES execution failed: ${errorMsg}`);

        // Mark campaign as failed in Supabase
        if (input.campaignId > 0) {
            await patchRow(env, 'strike_campaigns', {
                status: 'failed',
                failure_reason: errorMsg,
            }, 'id', input.campaignId);
        }

        return {
            campaignId: input.campaignId,
            sesMessageId: '',
            status: 'failed',
            scheduledAt: new Date().toISOString(),
            error: errorMsg,
        };
    }
}
